#ifndef PLUMMET_TYPE_H
#define PLUMMET_TYPE_H

typedef enum PLUMMET_TYPE {
	PLUMMET_TYPE_INT,
	PLUMMET_TYPE_DOUBLE,
	PLUMMET_TYPE_STRING,
	PLUMMET_TYPE_MAP,
	PLUMMET_TYPE_LIST,
} PLUMMET_TYPE;

#endif // PLUMMET_TYPE_H