build_win_test_1:
	@x86_64-w64-mingw32-g++ -static -static-libgcc -static-libstdc++ -I../cli-colors/ test.cpp

build_win_test_2:
	@x86_64-w64-mingw32-g++ -static -static-libgcc -static-libstdc++ -I../cli-colors/ test2.cpp
