all:
	clang++ test-toml.cpp ../../../compile/internal/token/token.cpp -I../../../compile/internal/token ../../../compile/internal/lexer/lexer.cpp -I../../../compile/internal/lexer ../../../compile/internal/error/error.cpp -I../../../compile/internal/error
